version: '3.7'
services:
    flask:
        build: .
        command: flask run --host=0.0.0.0
        ports:
            - "5000:5000"
        environment:
            - DATABASE_URL=postgresql://postgres:password@postgres:5432/multi_user_service
            - FLASK_APP=app.py
        depends_on:
            - postgres
    postgres:
        image: postgres:12-alpine
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=password
            - POSTGRES_DB=multi_user_service