"""del photo field from Post

Revision ID: 1d744937816e
Revises: 2f49b0b8e414
Create Date: 2021-04-03 13:17:33.750264

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1d744937816e'
down_revision = '2f49b0b8e414'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'tags')
    op.drop_column('posts', 'picture_path')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('picture_path', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('posts', sa.Column('tags', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
