"""add Posts table

Revision ID: 2f49b0b8e414
Revises: 63ede23e3932
Create Date: 2021-04-01 16:33:45.004946

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2f49b0b8e414'
down_revision = '63ede23e3932'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('author', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('topic', sa.String(), nullable=True),
    sa.Column('start', sa.DateTime(), nullable=True),
    sa.Column('end', sa.DateTime(), nullable=True),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('tags', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('create_date', sa.DateTime(), nullable=True),
    sa.Column('update_date', sa.DateTime(), nullable=True),
    sa.Column('picture_path', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['author'], ['users.email'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_posts_author'), 'posts', ['author'], unique=False)
    op.create_index(op.f('ix_posts_create_date'), 'posts', ['create_date'], unique=False)
    op.create_index(op.f('ix_posts_start'), 'posts', ['start'], unique=False)
    op.create_index(op.f('ix_posts_title'), 'posts', ['title'], unique=False)
    op.create_index(op.f('ix_posts_topic'), 'posts', ['topic'], unique=False)
    op.create_index(op.f('ix_posts_update_date'), 'posts', ['update_date'], unique=False)
    op.drop_table('sal_emp')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sal_emp',
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('pay_by', postgresql.ARRAY(sa.INTEGER()), autoincrement=False, nullable=True),
    sa.Column('description', postgresql.ARRAY(sa.TEXT()), autoincrement=False, nullable=True)
    )
    op.drop_index(op.f('ix_posts_update_date'), table_name='posts')
    op.drop_index(op.f('ix_posts_topic'), table_name='posts')
    op.drop_index(op.f('ix_posts_title'), table_name='posts')
    op.drop_index(op.f('ix_posts_start'), table_name='posts')
    op.drop_index(op.f('ix_posts_create_date'), table_name='posts')
    op.drop_index(op.f('ix_posts_author'), table_name='posts')
    op.drop_table('posts')
    # ### end Alembic commands ###
